name: flutter_template
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: 7.4.0
  dio: 5.2.1+1
  elementary: 2.0.0
  firebase_core: 2.14.0
  firebase_crashlytics: 3.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logger: 1.4.0
  provider: 6.0.5
  retrofit: 4.0.1
  shared_preferences: 2.1.2
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: 2.4.5
  elementary_test: 1.1.3
  flutter_test:
    sdk: flutter
  json_serializable: 6.7.0
  retrofit_generator: 7.0.1
  surf_lint_rules: 2.1.0

environment:
  sdk: ">=3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
